<h3>Attribution</h3>
<p>The following <a href="http://creativecommons.org/licenses/by/2.0/" target="_blank">CC licensed</a> images are used on this site:</p>
<ul>
    <li>
        <a href="http://www.flickr.com/photos/kevinshine/10597406823" target="_blank" class="original-image">
            <img src="/images/attribution/10597406823_e1e624c732_s.jpg" alt="kev-shine">
        </a>
        <p>By: <a href="http://www.flickr.com/photos/kevinshine" target="_blank">kev-shine</a></p>
    </li>
    <li>
        <a href="http://www.flickr.com/photos/fncll/6847365223" target="_blank" class="original-image">
            <img src="/images/attribution/6847365223_4b5bdabf97_s.jpg" alt="ChrisL_AK">
        </a>
        <p>By: <a href="http://www.flickr.com/photos/fncll" target="_blank">Chris Lott (ChrisL_AK)</a></p>
    </li>
    <li>
        <a href="http://www.flickr.com/photos/jasonahowie/8583949219" target="_blank" class="original-image">
            <img src="/images/attribution/8583949219_f55657573e_s.jpg" alt="Jason A. Howie">
        </a>
        <p>By: <a href="http://www.flickr.com/photos/jasonahowie" target="_blank">Jason Howie (Jason A. Howie)</a></p>
    </li>
    <li>
        <a href="http://www.flickr.com/photos/artberri/5132516289" target="_blank" class="original-image">
            <img src="/images/attribution/5132516289_e2586cccab_s.jpg" alt="artberri">
        </a>
        <p>By: <a href="http://www.flickr.com/photos/artberri" target="_blank">Alberto Varela (artberri)</a></p>
    </li>
    <li>
        <a href="http://www.flickr.com/photos/ruiwen/3260094840" target="_blank" class="original-image">
            <img src="/images/attribution/3260094840_6f45be6c91_s.jpg" alt="ruiwen">
        </a>
        <p>By: <a href="http://www.flickr.com/photos/ruiwen" target="_blank">Ruiwen Chua (ruiwen)</a></p>
    </li>
    <li>
        <a href="http://www.flickr.com/photos/webtreatsetc/5495803712" target="_blank" class="original-image">
            <img src="/images/attribution/5495803712_360c7c0f79_s.jpg" alt="webtreats">
        </a>
        <p>By: <a href="http://www.flickr.com/photos/webtreatsetc" target="_blank">webtreats</a></p>
    </li>
    <li>
        <a href="http://www.flickr.com/photos/sundve/3744159600" target="_blank" class="original-image">
            <img src="/images/attribution/3744159600_eff0377c6a_s.jpg" alt="Sundve">
        </a>
        <p>By: <a href="http://www.flickr.com/photos/sundve" target="_blank">Espen Sundve (Sundve)</a></p>
    </li>
</ul>
