<!DOCTYPE html>
<html>
    <head>
        <title>PHPoAuthLib</title>
        <meta charset="utf-8">
        <script>'article aside footer header main nav section time'.replace(/\w+/g,function(n){document.createElement(n)})</script>
        <link href="/style/style.css" rel="stylesheet" media="screen">
    </head>
    <body>
        <a href="https://github.com/Lusitanian/PHPoAuthLib">
            <img class="github-badge" src="https://github-camo.global.ssl.fastly.net/652c5b9acfaddf3a9c326fa6bde407b87f7be0f4/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f72696768745f6f72616e67655f6666373630302e706e67" alt="Fork me on GitHub" data-canonical-src="https://s3.amazonaws.com/github/ribbons/forkme_right_orange_ff7600.png">
        </a>
        <div id="content">
            <h1>PHPoAuthLib</h1>
            <h2>Home of the <span>PHP 5.3+ Oauth Consumer library</span></h2>
            <div class="badges">
                <img src="https://poser.pugx.org/lusitanian/oauth/v/stable.png" alt="Latest stable version">
                <img src="https://poser.pugx.org/lusitanian/oauth/downloads.png" alt="Number of packagist downloads">
            </div>
            <div class="intro">
                <h3>Easily connect to your favorite online services</h3>
                <h4>Free open source Oauth library</h4>
                <div class="image-container">
                    <img src="/images/explained-1.jpg" class="first" alt="Social media">
                    <img src="/images/explained-3.jpg" class="" alt="Elephpants">
                    <img src="/images/explained-2.jpg" class="last" alt="Social media explained">
                </div>
            </div>
            <div class="features">
                <h3>Documentation and information</h3>
                <h4>Find all the API information you need</h4>
                <ul>
                    <li>
                        <img src="/images/demo.png" alt="Demo">
                        <h5><a href="https://demo.phpoauthlib.com" target="_blank">Demo</a></h5>
                        <p>A demo website used to test and debug the library with the different services. This can also be used to find documentation about service API calls.</p>
                    </li>
                    <li>
                        <img src="/images/documentation.jpg" alt="Documentation">
                        <h5><a href="/documentation" target="_blank">Documentation</a></h5>
                        <p>Yes! We should totally have documentation at some point!</p>
                    </li>
                    <li>
                        <img src="/images/services.jpg" alt="Supported services">
                        <h5><a href="#services">Supported services</a></h5>
                        <p>Click here for the list of supported services.</p>
                    </li>
                    <li>
                        <img src="/images/contributors.jpg" alt="Contributors">
                        <h5><a href="https://github.com/Lusitanian/PHPoAuthLib/graphs/contributors" target="_blank">Contributors</a></h5>
                        <p>Special thanks to all the contributors of the project!</p>
                    </li>
                </ul>
            </div>
            <div class="services">
                <h3 id="services">Supported services</h3>
                <h4>Oauth 1</h4>
                <ul>
                    <li><img src="/images/services/bitbucket.png" alt="BitBucket" title="BitBucket"></li>
                    <li><img src="/images/services/etsy.jpg" alt="Etsy" title="Etsy"></li>
                    <li><img src="/images/services/fitbit.png" alt="FitBit" title="FitBit"></li>
                    <li><img src="/images/services/flickrt.jpg" alt="Flickr" title="Flickr"></li>
                    <li><img src="/images/services/tumbler.png" alt="Tumbler" title="Tumbler"></li>
                    <li><img src="/images/services/twittert.jpg" alt="Twitter" title="Twitter"></li>
                </ul>
                <h4>Oauth 2</h4>
                <ul>
                    <li><img src="/images/services/amazon.png" alt="Amazon" title="Amazon"></li>
                    <li><img src="/images/services/bitly.jpg" alt="Bitly" title="Bitly"></li>
                    <li><img src="/images/services/box.png" alt="Box" title="Box"></li>
                    <li><img src="/images/services/dailymotion.png" alt="Dailymotion" title="Dailymotion"></li>
                    <li><img src="/images/services/dropbox.png" alt="Dropbox" title="Dropbox"></li>
                    <li><img src="/images/services/facebookt.jpg" alt="Facebook" title="Facebook"></li>
                    <li><img src="/images/services/foursquare.jpg" alt="Foursquare" title="Foursquare"></li>
                    <li><img src="/images/services/github.png" alt="GitHub" title="GitHub"></li>
                    <li><img src="/images/services/google.gif" alt="Google" title="Google"></li>
                    <li><img src="/images/services/harvest.png" alt="Harvest" title="Harvest"></li>
                    <li><img src="/images/services/heroku.jpg" alt="Heroku" title="Heroku"></li>
                    <li><img src="/images/services/instagramt.png" alt="Instagram" title="Instagram"></li>
                    <li><img src="/images/services/linkedint.jpg" alt="LinkedIn" title="LinkedIn"></li>
                    <li><img src="/images/services/mailchimp.png" alt="MailChimp" title="MailChimp"></li>
                    <li><img src="/images/services/microsoft.jpg" alt="Microsoft" title="Microsoft"></li>
                    <li><img src="/images/services/paypal.jpg" alt="PayPal" title="PayPal"></li>
                    <li><img src="/images/services/runkeeper.jpg" alt="RunKeeper" title="RunKeeper"></li>
                    <li><img src="/images/services/soundcloud.png" alt="Soundcloud" title="Soundcloud"></li>
                    <li><img src="/images/services/vkontaktet.png" alt="VKontakte" title="VKontakte"></li>
                    <li><img src="/images/services/yammer.jpg" alt="Yammer" title="Yammer"></li>
                    <li><img src="/images/services/redditt.jpg" alt="Reddit" title="Reddit"></li>
                </ul>
            </div>
            <div class="installation">
                <h3>Installation</h3>
                <h4>The easiest way to install the project is by using composer</h4>
<pre>{
    "require": {
        "lusitanian/oauth": "~0.2"
    }
}</pre>
            </div>
            <h2>Home of the <span>PHP 5.3+ Oauth Consumer library</span></h2>
            <div class="footer">
                <ul>
                    <li><a href="#">About</a></li>
                    <li><a href="/attribution">Attribution</a></li>
                    <li><a href="#">Contact</a></li>
                </ul>
                <p>© 2014 PHPoAuthLib. All Rights Reserved.</p>
            </div>
        </div>
        <script src="/js/main.js"></script>
    </body>
</html>
