<!DOCTYPE html>
<html>
    <head>
        <title>PHPoAuthLib</title>
        <meta charset="utf-8">
        <script>'article aside footer header main nav section time'.replace(/\w+/g,function(n){document.createElement(n)})</script>
        <link href="/style/style.min.css" rel="stylesheet" media="screen">
    </head>
    <body>
        <a href="https://github.com/Lusitanian/PHPoAuthLib">
            <img class="github-badge" src="/style/github-badge.png" alt="Fork me on GitHub">
        </a>
        <div id="content">
            <h1>PHPoAuthLib</h1>
            <h2>Home of the <span>PHP 5.3+ Oauth Consumer library</span></h2>
            <div class="badges">
                <img src="https://poser.pugx.org/lusitanian/oauth/v/stable.png" alt="Latest stable version">
                <img src="https://poser.pugx.org/lusitanian/oauth/downloads.png" alt="Number of packagist downloads">
            </div>
            <div class="intro">
                <h3>Easily connect to your favorite online services</h3>
                <h4>Free open source Oauth library</h4>
                <div class="image-container">
                    <img src="/images/explained-1.jpg" class="first" alt="Social media">
                    <img src="/images/explained-3.jpg" class="" alt="Elephpants">
                    <img src="/images/explained-2.jpg" class="last" alt="Social media explained">
                </div>
            </div>
            <div class="features">
                <h3>Documentation and information</h3>
                <h4>Find all the API information you need</h4>
                <ul>
                    <li>
                        <img src="/images/demo.png" alt="Demo">
                        <h5><a href="https://demo.phpoauthlib.com" target="_blank">Demo</a></h5>
                        <p>A demo website used to test and debug the library with the different services. This can also be used to find documentation about service API calls.</p>
                    </li>
                    <li>
                        <img src="/images/documentation.jpg" alt="Documentation">
                        <h5><a href="/documentation" target="_blank">Documentation</a></h5>
                        <p>Yes! We should totally have documentation at some point!</p>
                    </li>
                    <li>
                        <img src="/images/services.jpg" alt="Supported services">
                        <h5><a href="#services">Supported services</a></h5>
                        <p>Click here for the list of supported services.</p>
                    </li>
                    <li>
                        <img src="/images/contributors.jpg" alt="Contributors">
                        <h5><a href="https://github.com/Lusitanian/PHPoAuthLib/graphs/contributors" target="_blank">Contributors</a></h5>
                        <p>Special thanks to all the contributors of the project!</p>
                    </li>
                </ul>
            </div>
            <div class="services">
                <h3 id="services">Supported services</h3>
                <h4>Oauth 1</h4>
                <ul>
                    <li class="bitbucket" title="BitBucket"></li>
                    <li class="etsy" title="Etsy"></li>
                    <li class="fitbit" title="FitBit"></li>
                    <li class="flickrt" title="Flickr"></li>
                    <li class="tumbler" title="Tumblr"></li>
                    <li class="twittert" title="Twitter"></li>
                </ul>
                <h4>Oauth 2</h4>
                <ul>
                    <li class="amazon" title="Amazon"></li>
                    <li class="bitly" title="Bitly"></li>
                    <li class="box" title="Box"></li>
                    <li class="dailymotion" title="Dailymotion"></li>
                    <li class="dropbox" title="Dropbox"></li>
                    <li class="facebookt" title="Facebook"></li>
                    <li class="foursquare" title="Foursquare"></li>
                    <li class="github" title="GitHub"></li>
                    <li class="google" title="Google"></li>
                    <li class="harvest" title="Harvest"></li>
                    <li class="heroku" title="Heroku"></li>
                    <li class="instagramt" title="Instagram"></li>
                    <li class="linkedint" title="LinkedIn"></li>
                    <li class="mailchimp" title="MailChimp"></li>
                    <li class="microsoft" title="Microsoft"></li>
                    <li class="paypal" title="PayPal"></li>
                    <li class="redditt" title="Reddit"></li>
                    <li class="runkeeper" title="RunKeeper"></li>
                    <li class="soundcloud" title="Soundcloud"></li>
                    <li class="vkontaktet" title="VKontakte"></li>
                    <li class="yammer" title="Yammer"></li>
                </ul>
            </div>
            <div class="installation">
                <h3>Installation</h3>
                <h4>The easiest way to install the project is by using composer</h4>
<pre>{
    "require": {
        "lusitanian/oauth": "~0.2"
    }
}</pre>
            </div>
            <h2>Home of the <span>PHP 5.3+ Oauth Consumer library</span></h2>
            <div class="footer">
                <ul>
                    <li><a href="#">About</a></li>
                    <li><a href="/attribution">Attribution</a></li>
                    <li><a href="#">Contact</a></li>
                </ul>
                <p>© 2014 PHPoAuthLib. All Rights Reserved.</p>
            </div>
        </div>
        <script src="/js/main.min.js"></script>
    </body>
</html>
